Add Rspec Max Configurations
TRANSREPORT/transreport-rails-style pull request #1
Opened 2021-07-01 14:24 UTC by J-Hernandez1

**Description:**

As per title

Rubocop Rules changed:

[Rspec/NestedGroups](https://docs.rubocop.org/rubocop-rspec/2.1/cops_rspec.html#rspecnestedgroups) - Voted to move from default of 3 to 5. This allows multiple indentations within the file of up to 5, after viewing team was happy to raise the number as it didn't make the code less readable. 5 was the max amount that Defect Report had and on team inspection the amount of indentation was deemed suitable to raise as the Max value

Rubocop Rules shelved for future discussion:

[Rspec/ExampleLength](https://docs.rubocop.org/rubocop-rspec/2.1/cops_rspec.html#rspecexamplelength) - voted to raise from 5 to 15 across all codebases as 5 was too restricting and those of around around 15 still looked neat and necessary

[Rspec/MultipleExpectations](https://docs.rubocop.org/rubocop-rspec/2.2/cops_rspec.html#rspecmultipleexpectations) removed back to default to avoid additional rubocop.yml files. Agreed upon team solution for up to 5 MultipleExpectations is the use of `Aggregate features` block with expects placed within the block.

**Ticket/Issue Reference:**  

**Testing Plan:**

Pipeline

**Breaking Changes**:

- [x] Any breaking changes have been disclosed to the relevant party/parties

**Checklist:**

- [x] [Accompanying documentation](https://transreport.atlassian.net/wiki/spaces/ENG/pages/1766752263/What+is+Accompanying+Documentation) provided (where necessary)
- [ ] Manual testing was successful
- [x] Automated tests cover the content of this PR
- [x] PR appropriately labelled
- [x] Reviewers and assignees appropriately set
- [x] Tickets raised for any out-of-scope work identified

2021-07-01 14:47 UTC, Stivaros approved these changes

2021-07-01 17:10 UTC, yankovskiid approved these changes

2021-07-01 17:14 UTC, jasylwong commented
@J-Hernandez1 Please can you update our [linting documentation](https://transreport.atlassian.net/wiki/spaces/ENG/pages/1513521153/Linting) appropriately, in particular the rules table.

2021-07-01 17:24 UTC, jasylwong reviewed
In addition to the one question, please can you update our [linting documentation ](https://transreport.atlassian.net/wiki/spaces/ENG/pages/1513521153/Linting) appropriately, in particular the rules table. Happy for you to do that after this PR is merged in.

2021-07-01 17:24 UTC, jasylwong commented on transreport-rails.yml
> +  Max: 5
Sorry, can't remember - did we say extend the max for _every_ file, or only for view level files?

2021-07-02 09:56 UTC, J-Hernandez1 commented on transreport-rails.yml
> +  Max: 5
I'm not sure if there was a way to have a different number for specific files/folder, only across the board was configurable.

2021-07-02 15:49 UTC, jasylwong commented on transreport-rails.yml
> +  Max: 5
Did any potential solutions arise when you researched such a way?

2021-07-02 15:53 UTC, J-Hernandez1 commented on transreport-rails.yml
> +  Max: 5
None arised from my research into it, [rubocop](https://docs.rubocop.org/rubocop-rspec/2.2/cops_rspec.html#rspecmultipleexpectations) seems limited on this rule to only a configurable  change in the Max Integer only whereas some rules have a bit more flexibility in their configuration options

2021-07-05 08:04 UTC, jasylwong commented on transreport-rails.yml
> +  Max: 5
There is [a way to set different configuration for different files](https://stackoverflow.com/a/55277985).

What is your opinion on it?

2021-07-08 12:27 UTC, Stivaros commented on transreport-rails.yml
> +  Max: 5
I had the same question in my mind. Let's do more research because I don't want to enable multiple expectations in unit tests.

2021-07-13 15:17 UTC, jasylwong commented on transreport-rails.yml
> +  Max: 5
Yep, you're correct. What's your _opinion_ of that solution though?

2021-07-13 15:59 UTC, J-Hernandez1 commented on transreport-rails.yml
> +  Max: 5
I think its a good solution to apply the default rule to unit tests if we're happy of having a non spec file alongside spec files. I can't seem to find anything as a way of testing it will work as intended before merging the changes in and trying it within an active codebase?

2021-07-14 08:58 UTC, jasylwong commented on transreport-rails.yml
> +  Max: 5
Whilst I am glad we have a way of setting different rules for different files, I'm slightly averse to having another separate file for specs in every project, because:
- it defeats the purpose of having everything linting related in the centralised transreport-style repo
- rules may diverge across projects if different changes are made to those spec files in each repo
- more files = more management. Also, if someone doesn't know about the file in the spec directory, they may not understand why something different is happening to what they see in tranreport-style

If you can't find another solution, I suggest you bring this to the wider Ruby dev team for discussion, esp as it's a team decision

2021-07-15 09:08 UTC, jasylwong commented on transreport-rails.yml
> +  Max: 15
Did we discuss '[CountAsOne](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexamplelength)'?

Do you think we should use it? If so, for which object types?

2021-07-15 11:15 UTC, J-Hernandez1 commented on transreport-rails.yml
> +  Max: 15
We didn't discuss the `CountAsOne` option as a team. For me personally I'm a bit adverse to using that as it seems a lot harder to follow along if I was to read test scripts and potentially take longer to amend as it's unfamiliar. I personally quite like the per line structure when reading Rspec files but we could have a discussion if you think it can be useful to us?

2021-07-15 13:04 UTC, jasylwong commented on transreport-rails.yml
> +  Max: 15
I would argue from one perspective it makes it easier to follow; you can just assume the whole object only takes one line.

What if you have an array that is 14 sentences, so needs to have separate lines for each? Then you only have 1 line left to actually write code for the test.

So I would be 'for' it. But again, it's a team decision that warrants asking everyone.

2021-07-15 14:57 UTC, Stivaros requested changes
Too much bike-shedding. Get rid of contentious stuff, get team agreement and package a release as agreed. We can release this gem as many times as we want :)

Thank you for maintaining high standards @jasylwong, much appreciated.

2021-07-15 14:57 UTC, Stivaros commented on transreport-rails.yml
> +  Max: 15
Let's move quicker... remove this rule until properly discussed. We could theoretically merge `v0.2.0` with the `NestedGroups` rule and release `v0.3.0` a day later if we came to a conclusion.

Smaller releases = quicker = better. Too much discussion on this release already.

2021-07-15 14:57 UTC, Stivaros commented on transreport-rails.yml
> +  Max: 5
With my above comment in mind, I genuinely can't remember this being agreed in the meeting. I remember us not being sure what is was and then discovering what it was. If this was agreed then let's merge and crack on.

2021-07-15 16:26 UTC, J-Hernandez1 commented on transreport-rails.yml
> +  Max: 5
Removed `MultipleExpectations` with `NestedGroups` being the only new addition. The number 5 was decided as that was the max amount DR had and on viewing we didn't find that to be an undesirable trait to have within the code.

2021-07-15 18:30 UTC, Stivaros approved these changes

2021-07-16 07:40 UTC, yankovskiid approved these changes

2021-07-16 08:01 UTC, jasylwong approved these changes

2021-07-16 10:26 UTC, merged